version: 2.1
jobs:
    test-go:
        docker:
            - image: circleci/golang:1.17
        resource_class: medium
        steps:
            - checkout
            - run:
                  "cd ..; git clone https://github.com/kubernetes/kubernetes.git; cd kubernetes; git
                  checkout v1.23.1; make; cd ../fakeapiserver"
            - run: "go test ./..."
workflows:
    version: 2
    build_and_test:
        jobs:
            - test-go
